Add Support for Schedules in Views
NubeIO/rubix-ce pull request #1352
Opened 2023-08-05 16:46 UTC by ayush-shta

## Tasks:
1. Extract out components of draggable nav items into separate files with folder/file restructuring
2. Create component for draggable sub menu schedules component
3. Update class name for draggable menu item
4. Create a separate component for draggable menu item
5. Create draggable config types, pass draggable config type object through drag items
6. Manage configuration for `SCHEDULES_ITEM` drop
7. Rename create widget for device item
8. Create modal for schedule item create widget
9. Handle edit action based on widget class
10. Remove react-dnd after findings mentioned here: https://github.com/NubeIO/rubix-ce/pull/1357

**TODO:** Show flutter widget when creating/updating schedules item widget

### Video demonstration:

https://github.com/NubeIO/rubix-ce/assets/33564406/0fd40b52-3767-432d-88e6-b1c7b5a23e58

2023-08-06 03:40 UTC, RaiBnod commented
A couple of concerns from the video:
- We don't need the network selection here, the schedule is independent of the network things -- we are selecting the network at first
- When we do edit, it needs to show host configurator as in Points -- may be it has the implementation but I don't see it in the video

2023-08-14 10:04 UTC, riteshakya037 requested changes
The ability to modify current widgets is no more functional, and altering new widgets also fails to establish the initial name value. I have included a recording demonstrating this issue.

https://github.com/NubeIO/rubix-ce/assets/9533579/5317850e-5b4e-4dbe-8040-d63f31175126
Furthermore, the widget preview is absent during the creation of a Schedule. However, I intend to create a separate ticket for this, as it is not considered a critical obstacle.

2023-08-14 17:24 UTC, riteshakya037 approved these changes

2023-08-14 17:27 UTC, merged

2023-08-14 17:27 UTC, riteshakya037 commented
Create #1370 for missing preview for the schedule widget while creation.